### ISSUE TITLE
Older World

### ISSUE THREAD

**Issue by Nazgah** [FimbulvetrOW/BetterAI#2]
Hey, not sure where to contact you so I'll try here. Will you be updating Older world mod compilation to latest ver. currently 1.0.73323 ?

**Comment by FimbulvetrOW** [comment]
Yes, I plan to, but I've been getting distracted a lot lately. If I fail to update this week, you can probably assume this mod is dead.

**Comment by Nazgah** [comment]
No biggie, it is still a fun modpack I kept a backup of last working version anyway if I'll be going back to it. Thanks for your work.

**Comment by FimbulvetrOW** [comment]
While going back is probably possible with old versions of the game, I think that's a bit too much effort, just for a mod. 
Anyway I updated now. I hope I didn't break too much.
Please contact me on discord if you want timely answers :)
